import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import SmoothScroll from "./components/SmoothScroll";
import AnimateSectionTitle from "./components/AnimateSectionTitle";
import HeaderAnimation from "./components/HeaderAnimation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SmoothScroll>
          <Header />
          {children}
          <Footer />
          <AnimateSectionTitle />
        </SmoothScroll>
      </body>
    </html>
  );
}
